FROM node:23.7-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy application source code
COPY server/chat_server/server.js ./

# Expose the application port
EXPOSE 3001

# Command to run the application
CMD ["node", "server.js"]

