# Stage 1: Build stage
FROM python:3.12-slim-bookworm AS builder

WORKDIR /app

# Install dependencies
COPY llm/requirements.txt .
RUN apt-get update && apt-get install -y \
    gcc \
    libc-dev \
    curl \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

# Stage 2: Runtime stage
# FROM python:3.12-slim-bookworm

WORKDIR /app

# Copy installed packages from builder
# COPY --from=builder /root/.local /root/.local
COPY ./llm .

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

EXPOSE 36430

CMD ["python", "main.py", "--host", "0.0.0.0", "--port", "36430"]
